[project]
name = "Argoverse-SF-Optimization-Baseline"
requires-python = ">=3.8"

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
strict = true

[tool.black]
line-length = 120