cfg_name: nsfp_sheet_loss
model_name: nsfp
device: cuda
timing: false

arch:
  filter_size: 128
  activ: relu
  pos_enc: False
  L: 4
  pos_scale: 100
  backward_flow: True
  motion_compensate: True
  refine: False

optim:
  type: Adam
  grad_clip: 0.1
  args:
    lr: 0.004
    weight_decay: 0.000
  sched:
    type: StepLR
    args:
      step_size: 500
      
  debug: false
  iters: 2000
  early_patience: 100
  chamfer_radius: 2
  loss:
    type: sheet
    models_root: ../beyond-chamfer/world_sheet/outputs/impl_new_default/nuscenes/
  
