cfg_name: nsfp
model_name: nsfp
device: cuda
timing: false

arch:
  filter_size: 128
  activ: relu
  pos_enc: False
  L: 4
  pos_scale: 100
  backward_flow: True
  motion_compensate: True
  refine: False

optim:
  type: Adam
  args:
    lr: 0.004
    weight_decay: 0.0
  sched:
    type: StepLR
    args:
      step_size: 2000
      
  debug: false
  iters: 2000
  early_patience: 100
  chamfer_radius: 2
  loss:
    type: chamfer
    models_root: 
  
