cfg_name: nsfp_sheet_loss
model_name: nsfp
device: cuda
timing: false

arch:
  filter_size: 128
  activ: relu
  pos_enc: False
  L: 4
  pos_scale: 100
  backward_flow: True
  motion_compensate: True
  refine: False

optim:
  type: SGD
  args:
    lr: 0.1
    weight_decay: 0.0
    momentum: 0.9
  sched:
    type: StepLR
    args:
      step_size: 1000
      
  debug: false
  iters: 5000
  early_patience: 500
  chamfer_radius: 2
  loss:
    type: sheet
    models_root: ../beyond-chamfer/world_sheet/outputs/impl_new_default/nuscenes/
  
