cfg_name: nsfp_sheet_loss
model_name: nsfp
device: cuda
timing: false

arch:
  filter_size: 128
  activ: relu
  pos_enc: False
  L: 4
  pos_scale: 100
  backward_flow: True
  motion_compensate: True
  refine: False

optim:
  type: Adam
  args:
    lr: 0.004
    weight_decay: 0.0001
  sched:
    type: ReduceLROnPlateau
    args:
      factor: 0.1
      patience: 100
      
  debug: false
  iters: 5000
  early_patience: 200
  chamfer_radius: 2
  loss:
    type: sheet
    models_root: ../beyond-chamfer/world_sheet/outputs/impl_new_default/nuscenes/
  
